# Generated by Django 5.1 on 2024-08-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('superficie', models.IntegerField()),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IntrusionMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(upload_to='photos/IntrusionMaison/')),
                ('camera_maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cameramaison')),
            ],
        ),
        migrations.AddField(
            model_name='cameramaison',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maison'),
        ),
        migrations.CreateModel(
            name='MembreMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maison')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeSurveillanceMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maison')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMembreMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(upload_to='photos/MembreMaison/')),
                ('membre_maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membremaison')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/Utilisateur/')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profil')),
            ],
        ),
        migrations.AddField(
            model_name='maison',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_utilisateur', to='api.utilisateur')),
            ],
        ),
    ]
