# Generated by Django 5.1 on 2024-08-10 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='superficie',
        ),
        migrations.AddField(
            model_name='cameramaison',
            name='lien',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membremaison',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/MembreMaison/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhotoMembreMaison',
        ),
    ]
