# Generated by Django 5.1 on 2024-08-10 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_maison_prix_remove_maison_superficie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_ajout',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 21, 12, 56, 163480)),
        ),
    ]
