# Generated by Django 5.1 on 2024-08-10 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_utilisateur_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 21, 58, 57, 947447)),
        ),
        migrations.AlterField(
            model_name='membremaison',
            name='date_ajout',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 21, 43, 57, 948761)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_ajout',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 21, 43, 57, 947447)),
        ),
    ]
